# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20171209_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositions',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
