# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_propositions_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositions',
            name='answer',
            field=models.NullBooleanField(),
        ),
    ]
